os:
  linux

dist:
  trusty

language: node_js
node_js:
  - lts/*

script:
  - npm run docs:build

branches:
  only:
    - develop

git:
  quiet: true

deploy:
  strategy: git
  provider: pages
  cleanup: false
  token: $github_token
  keep_history: true
  local_dir: docs/.vuepress/dist