os:
  linux

dist:
  trusty

language: node_js
node_js:
  - lts/*

script:
  - npm run docs:build

before_deploy:
  - "echo zheilbron.com > docs/.vuepress/dist/CNAME"

branches:
  only:
    - develop

git:
  quiet: true

deploy:
  provider: pages:git
  token: $github_token
  edge: true
  cleanup: false
  keep_history: true
  local_dir: docs/.vuepress/dist
  target_branch: master
  on:
    branch: develop